---
- href: https://www.bmo.com/
  regex: \b(BMO's|BMO|BMO\s+website)\b
  title: BMO
- href: https://www.bmo.com/en-us/main/personal/checking-accounts/
  regex: \b(checking\s+accounts?|checking)\b
  title: Checking Accounts
- href: https://www.bmo.com/en-us/main/personal/savings-and-cds/
  regex: \b(savings\s+accounts?|savings)\b
  title: Savings Accounts, Money Markets and CDs
- href: https://www.bmo.com/en-us/main/personal/investments-and-retirement/
  regex: \b(investment options|investments?|investing|retirement|IRAs?|wealth\s+management)\b
  title: Investments and Retirement
- href: https://www.bmo.com/en-us/main/personal/credit-cards/
  regex: \b(credit\s+cards?)\b
  title: Credit Cards
- href: https://www.bmo.com/en-us/main/personal/mortgages/
  regex: \b(mortgages?)\b
  title: Mortgages
- href: https://www.bmo.com/en-us/main/personal/loans-and-lines-of-credit/
  regex: \b(loans?)\b
  title: Loans and Lines of Credit
- href: https://www.bmo.com/en-us/main/contact-us/
  regex: \b(financial advisors?|banker|contact)\b
  title: Contact Us
- href: https://our-impact.bmo.com/us/our-practices/climate-change/
  ignore_case: true
  regex: \b(climate change|renewable energy|environmental|sustainability|sustainable)\b
  title: Climate change
- href: https://our-impact.bmo.com/us/our-practices/diversity-and-inclusion/
  ignore_case: true
  regex: \b(diversity and inclusion|diverse and inclusive|diversity|inclusion)\b
  title: Diversity, equity and inclusion
- href: https://www.bmo.com/en-us/main/personal/online-banking/
  ignore_case: true
  regex: \b(online banking)\b
  title: BMO Digital Banking
