name: Build and Publish Docker Image

on:
  push:
    branches:
        - main
    paths:
        - llama2/Dockerfile
        - llama2/entrypoint.sh
        - .github/workflows/docker_build_llama2.yml
  schedule:
    - cron: '0 5 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./llama2
        file: ./llama2/Dockerfile
        push: true
        tags: lancespeelmon/llama2-cpp-python:latest
